import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth/requireAdmin'
import { createServiceClient } from '@/lib/supabase/service'

// ~100 years — Supabase has no "permanent" ban, so we use a duration far beyond
// any realistic account lifetime. Reactivation clears it with 'none'.
const BAN_DURATION = '876000h'

/**
 * Admin-only: deactivate or reactivate a staff member.
 *
 * Deactivation is a SOFT operation — we ban the Supabase Auth user so they can
 * no longer sign in, but we deliberately keep their `profiles` row. Historical
 * attribution (deal_sheets.generated_by, leads.assigned_to) references that row
 * via ON DELETE SET NULL foreign keys; a hard delete would orphan that history
 * and break "Generated by [Name]" on past deal sheets. Banning preserves it and
 * is fully reversible.
 */
export async function POST(request: NextRequest) {
  const auth = await requireAdmin()
  if (!auth.ok) {
    return NextResponse.json({ error: auth.error }, { status: auth.status })
  }

  let body: { userId?: unknown; action?: unknown }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
  }

  const userId = typeof body.userId === 'string' ? body.userId : ''
  const action = body.action === 'reactivate' ? 'reactivate' : 'deactivate'

  if (!userId) {
    return NextResponse.json({ error: 'Missing userId' }, { status: 400 })
  }

  // An admin must never be able to deactivate their own account — enforced here
  // server-side in addition to the UI hiding the control on the current row.
  if (userId === auth.userId) {
    return NextResponse.json(
      { error: 'You cannot deactivate your own account.' },
      { status: 400 }
    )
  }

  const service = createServiceClient()
  const { error } = await service.auth.admin.updateUserById(userId, {
    ban_duration: action === 'reactivate' ? 'none' : BAN_DURATION,
  })

  if (error) {
    console.error('updateUserById (ban) failed:', error)
    return NextResponse.json(
      { error: 'Failed to update account.' },
      { status: 500 }
    )
  }

  return NextResponse.json({ success: true, action })
}
